### ISSUE TITLE
Update README.md for Lulu etc

### ISSUE THREAD

**Issue by nealmcb** [mandiberg/printwikipedia#11]
The README.md file is about 2 years old, and for example still refers to using CreateSpace, while it seems that Lulu is used now.  Presumably there are other things to update.

This would also be a great place for statistics, and, now that the art exhibit is up and the publication is underway, for references e.g. to [Moving Wikipedia From Computer to Many, Many Bookshelves - The New York Times](http://www.nytimes.com/2015/06/17/books/moving-wikipedia-from-computer-to-many-many-bookshelves.html?_r=1), and [Wikipedia:Size in volumes - Wikipedia, the free encyclopedia](https://en.wikipedia.org/wiki/Wikipedia:Size_in_volumes)

Thanks for a fantastic piece of art and technology!

**Comment by nealmcb** [comment]
Statistics from interview at [7,473 volumes at 700 pages each: meet Print Wikipedia « Wikimedia blog](http://blog.wikimedia.org/2015/06/19/meet-print-wikipedia/):

 Each of the 7,473 volumes is made up of 700 pages, for a total of 5,244,11 pages. The Wikipedia Table of Contents is comprised of 63,372 pages in 91 volumes. The Wikipedia Contributor Appendix contains all 7,488,091 contributors to the English-language Wikipedia (nearly 7.5 Million).

**Comment by mandiberg** [comment]
Thanks for this @nealmcb. We've been swamped just getting all the files to upload. Working on a last round of the Table of Contents today (somehow the files are corrupt, and I have re-render them). Then a whole lot of cleanup and documentation!
